// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoVHRmxgCVeylyQnmwVnhWVANnKPhZ4f0',
    appId: '1:809732913368:web:40c85bcc7cafee9d18bfad',
    messagingSenderId: '809732913368',
    projectId: 'firebase-noti-naymyomhan',
    authDomain: 'fir-noti-naymyomhan.firebaseapp.com',
    storageBucket: 'firebase-noti-naymyomhan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1Pc2fbGyw8RE-pEZlZUY7CpiaMmdW5kY',
    appId: '1:809732913368:android:cf87820e7ef330b618bfad',
    messagingSenderId: '809732913368',
    projectId: 'firebase-noti-naymyomhan',
    storageBucket: 'firebase-noti-naymyomhan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4qcS9NZdpNUFnL3cdDcWey7MlNII1f4I',
    appId: '1:809732913368:ios:6fa6513c79db7ef718bfad',
    messagingSenderId: '809732913368',
    projectId: 'firebase-noti-naymyomhan',
    storageBucket: 'firebase-noti-naymyomhan.appspot.com',
    iosBundleId: 'com.example.firebaseNoti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4qcS9NZdpNUFnL3cdDcWey7MlNII1f4I',
    appId: '1:809732913368:ios:6fa6513c79db7ef718bfad',
    messagingSenderId: '809732913368',
    projectId: 'firebase-noti-naymyomhan',
    storageBucket: 'firebase-noti-naymyomhan.appspot.com',
    iosBundleId: 'com.example.firebaseNoti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoVHRmxgCVeylyQnmwVnhWVANnKPhZ4f0',
    appId: '1:809732913368:web:d144f13b8d776eff18bfad',
    messagingSenderId: '809732913368',
    projectId: 'firebase-noti-naymyomhan',
    authDomain: 'fir-noti-naymyomhan.firebaseapp.com',
    storageBucket: 'firebase-noti-naymyomhan.appspot.com',
  );
}
